version: '3'
services:
  api:
    container_name: my-api-local
    image: my-api-local
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - 9229:9229
    networks:
      - my-network
    restart: always
    volumes:
      - ./:/app

  nginx:
    container_name: my-nginx-local
    image: my-nginx-local
    build:
      context: .
      dockerfile: nginx/Dockerfile.local
    ports:
      - 443:443
    networks:
      - my-network
    restart: always

  db:
    container_name: my-db-local
    image: my-db-local
    build:
      context: .
      dockerfile: db/Dockerfile.local
    ports:
      - 3306:3306
    networks:
      - my-network
    restart: always

networks:
  my-network:
