version: '3.8'
services:
  backend:
    container_name: my_backend_pro
    image: my-backend-pro
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    environment:
      NODE_ENV: production
    ports:
      - 4444:4444
    networks:
      - my-backend-network

networks:
  my-backend-network:
