FROM node:16.15.1-alpine

ENV NODE_ENV=production
ENV MY_ENV=prod
EXPOSE 4444

WORKDIR /app
COPY . .
# yarn needs to ignore NODE_ENV because we need @nestjs/cli and so on.
RUN yarn install --silent --frozen-lockfile --production=false
RUN yarn build
CMD node dist/main
