version: '3'
services:
  api:
    image: ${DOCKER_REGISTRY}/api
    container_name: my-api-prod
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    networks:
      - my-network
    restart: always

  nginx:
    image: ${DOCKER_REGISTRY}/nginx
    container_name: my-nginx-prod
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    volumes:
      - /etc/letsencrypt/live/test.install.express/:/etc/nginx/certs/
    ports:
      - 443:443
    networks:
      - my-network
    restart: always

networks:
  my-network:
