name: Backend CD

on:
  push:
    branches: ["production"]
    paths:
      - "backend/**"
  workflow_dispatch:

env:
  docker-registry: 348881545837.dkr.ecr.ap-northeast-2.amazonaws.com
  docker-compose-file: docker-compose.prod.yml

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.docker-registry }}

      - name: Create ECR Repositories
        run: |
          for r in $(grep 'image: \${DOCKER_REGISTRY}' ${{ env.docker-compose-file }} | sed -e 's/^.*\///'); do
            aws ecr describe-repositories --repository-names $r || aws ecr create-repository --repository-name $r
          done

      - name: Set DOCKER_REGISTRY
        run: echo "DOCKER_REGISTRY=${{ env.docker-registry }}" >> $GITHUB_ENV

      - run: docker compose -f ${{ env.docker-compose-file }} build
      - run: docker compose -f ${{ env.docker-compose-file }} push

      - name: Set DOCKER_HOST
        run: echo "DOCKER_HOST=ssh://${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}" >> $GITHUB_ENV

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Append to known_hosts
        run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Login to ECR for remote Docker host
        uses: docker/login-action@v2
        with:
          registry: ${{ env.docker-registry }}

      - run: docker compose -f ${{ env.docker-compose-file }} pull
      - run: docker compose -f ${{ env.docker-compose-file }} up -d
      - run: docker image prune -f
